### ISSUE TITLE
How to use latest NGL (2.4.0) in nglview?

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#1058]
hi everyone

nglview has been using NGL 2.2.2 for a while and I am trying to upgrade to NGL 2.4.0.
However, I am getting below when running `npm install` in https://github.com/nglviewer/nglview/tree/master/js folder.

```
    ERROR in ./node_modules/ngl/dist/ngl.esm.js
    Module parse failed: Unexpected token (27:381727)
    You may need an appropriate loader to handle this file type.
    |  * @param {Float32Array} points - points
    |  * @param {Function} metric - metric
```

# So, any idea how to use the NGL 2.4.0 version? 

Thanks

**Comment by fredludlow** [comment]
Looking at the relevant file: https://www.[unpkg.com/ngl@2.4.0/dist/ngl.esm.js](https://www.unpkg.com/ngl@2.4.0/dist/ngl.esm.js)

That location (27:381727) is a spread operator (`...`).

I think maybe the webpack version in nglview doesn't know how to parse this?

Upgrading webpack may help, or may be a rabbit hole of other things to fix.

There is a plugin mentioned here: https://stackoverflow.com/questions/50327580/webpack-4-react-unexpected-token-spread-operator ("babel-plugin-transform-object-rest-spread") which might fix it.


I think the cause is the removal of `buble` from ngl on the basis that we didn't need to keep targetting IE11 and older browsers, but we could put back a compatibility build if there isn't any other way to fix it

**Comment by hainm** [comment]
> Looking at the relevant file: [https://www.[unpkg.com/ngl@2.4.0/dist/ngl.esm.js](https://www.unpkg.com/ngl@2.4.0/dist/ngl.esm.js)](https://www.%5Bunpkg.com/ngl@2.4.0/dist/ngl.esm.js%5D(https://www.unpkg.com/ngl@2.4.0/dist/ngl.esm.js))
> 
> That location (27:381727) is a spread/rest operator (`...`).
> 
> I think maybe the webpack version in nglview doesn't know how to parse this?
> 
> Upgrading webpack may help, or may be a rabbit hole of other things to fix.
> 
> There is a plugin mentioned here: https://stackoverflow.com/questions/50327580/webpack-4-react-unexpected-token-spread-operator ("babel-plugin-transform-object-rest-spread") which might fix it.
> 
> I think the cause is the removal of `buble` from ngl on the basis that we didn't need to keep targetting IE11 and older browsers, but we could put back a compatibility build if there isn't any other way to fix it

Thanks @fredludlow very much. I am able to upgrade to NGL 2.4.0 and this resolves lots of things (e.g: make it works with VSCode and nbclassic. Previously, I have to NGL build, one with 2.2.2 for jupyterlab and one with 2.1.1 for VSCode and nbclassic.

https://github.com/nglviewer/nglview/pull/1137
