### ISSUE TITLE
How to copy a stage?

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#668]
Hi,
Saying I have a `stage` with viewport A. Is it possble to copy it? thanks.

```
var new_stage = NGL.Stage('new_view_port')
new_stage.copy_from(existing_stage)
```

I guess this is similar to the question: how to deserialize a stage.

In `nglview`, to minor a `view`, `NGLWidget` needs to store the input commands from user and fire the commands to construct another view. (sometimes that works but sometimes that does not, e.g: display a view twice may trigger the screenshot (again).

**Comment by arose** [comment]
that is not implemented in NGL, it is however in Mol*... :)

**Comment by hainm** [comment]
@arose  do you mean to use MolStar to copy NGL.Stage or to use MolStar in `nglview instead of `NGL` or something else? Is it possible to implement in NGL?

**Comment by arose** [comment]
We should think about a Mol* based widget for Jupyter NB/Lab, maybe next year.

**Comment by hainm** [comment]
@arose my naive question: can a new `stage` reuse the current `stage.compList`? :D
or may be another way: is it easy to display a `stage` in different viewports?

**Comment by ppillot** [comment]
It is feasible thanks to JavaScript copy by reference, but it's hacky. Be
aware that when you remove from a stage a component that is shared between
two stages, you might have to patch the second copy in order to remove it
also from the second stage.
I've made it work in a project, but I unfortunately can't share that code.

Le mar. 25 juin 2019 à 13:08, Hai Nguyen <notifications@github.com> a
écrit :

**Comment by hainm** [comment]
> We should think about a Mol* based widget for Jupyter NB/Lab, maybe next year.

@arose 2022 year 😅: https://github.com/hainm/molstarview/
