### ISSUE TITLE
surface repr: opacity does not work with neglateIsolevel

### ISSUE THREAD

**Issue by hainm** [nglviewer/ngl#693]
Hi, please try with the .cube file in this https://github.com/arose/nglview/files/3579869/input.zip
- load it to http://nglviewer.org/ngl/
- With the surface repr, click "neglateIsolevel" and then adjust the "Opacity". There is no effect.

Here is the original context: https://github.com/arose/nglview/issues/785#issuecomment-528413612

thanks and cheers

**Comment by nickhine** [comment]
Hi, is anyone able to look into this? It's a quite irritating glitch which is preventing generation of the beautiful isosurface plots from ASE in jupyter notebooks.

**Comment by fredludlow** [comment]
I've had a bit of a look. For this use-case, we need to draw the negative iso-level surfaces inside-out (that is, flip the surface normals and triangle vertex order). However, it's not as simple as just doing this for all negative isolevels as things like electron density maps don't seem to require this behaviour (see [my branch](https://github.com/fredludlow/ngl/tree/693-negative-iso-transparency) and the parser/ccp4 example with a solid surface and negative iso level). I'll try to have a better look next week.

**Comment by nickhine** [comment]
Did anything come of looking into this bug with the flipped surface normals for negative isolevels? It's still there as of current versions as far as I can see.

**Comment by fredludlow** [comment]
Thanks for the prod @nickhine - it was a silly bug that blocked it before (and then I dropped the ball) - should be fixed with #792. You can grab built js from my website (see the PR) too if you want to check it's doing the right thing?

**Comment by nickhine** [comment]
Many thanks for looking into this.

I'd be happy to test but I'm not sure how to deploy that built ngl.dev.js file. I have nglview installed as a python package via pip, and that file doesn't seem to be a replacement for anything in that package.

**Comment by hainm** [comment]
@nickhine yeah, it's tricky to test with `nglview`. For now, you just need to upload your file to @fredludlow's website 
https://fredludlow.com/ngl/fix-693/examples/webapp.html?script=test/negative-iso

**Comment by nickhine** [comment]
Yep - I can confirm the opacity now works. Very nice. I'm looking forward to seeing that merged into nglview as well!

There is still the slight aesthetic niggle that even when the opacity is reduced, the isosurfaces still seem to mutually occlude each other so you cannot for example see a red lobe through a low-opacity blue one. But I imagine fixing that is probably technically challenging and might impact performance so no worries.

Many thanks.

**Comment by fredludlow** [comment]
You can get that effect by setting (for each of those surface representations) `side: 'front', depthWrite: false`

With those set, you can play around with opacity to get some nice effects (with opacity about 0.5 for both, front side no depthWrite):
![screenshot (3)](https://user-images.githubusercontent.com/900535/94261854-77181e00-ff2a-11ea-91f0-ffccbaaa94df.png)

but it doesn't always play nicely with the other representations! (with opacity about 0.75, front side, depthWrite false):
![screenshot (4)](https://user-images.githubusercontent.com/900535/94261946-93b45600-ff2a-11ea-81e2-9093fb6d3dd4.png)

I expect some of the weird over-intense/saturated colours would be fixed with @garyo's recent improvements. Maybe he or someone else with more webgl /3D rendering knowledge than me knows how to make this work generally?
