### ISSUE TITLE
limited atom selection

### ISSUE THREAD

**Issue by hoba87** [nglviewer/ngl#789]
When I want to select atoms from larger structures (~100.000 atoms) the selection is very limited.
E. g. with following representation with selection, the atoms 0, 1 and 2 are shown, while atoms 1000 and/or 10000 are not shown (the exact limit seems to depend on the number of atoms in the full structure)
```
    o.addRepresentation("spacefill", {
      side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, colorScheme: "element",
      sele: "@0,1,2,1000,10000"
    });
```

**Comment by fredludlow** [comment]
The @ rule uses NGL's internal atomindex, not serial numbers - (though usually that's only off-by-one if your serials start at 1 and don't have gaps).

Have you got an example file you can share?

**Comment by hoba87** [comment]
For the following example files I see only three atoms (1000, 10000, 48000) instead of the selected 6 atoms:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
</head>
<body style="background-color:grey; margin:0; padding:0; overflow:hidden">
  <script src="ngl.js"></script>
  <script>
    document.addEventListener("DOMContentLoaded", function () {
      var stage = new NGL.Stage("viewport");
      stage.loadFile("ngl.pdb").then(function(o) {
        o.addRepresentation("spacefill", {
          side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, colorScheme: "element",
          sele: "@1000,10000,48000,49000,50000,80000"
        });
        o.autoView();
      });
      stage.setParameters({cameraType: "orthographic"});
    });
  </script>
  <div id="viewport" style="width:800px; height:600px;">
  </div>
</body>
</html>
```
The zipped pdb file:
[ngl.pdb.gz](https://github.com/nglviewer/ngl/files/5245432/ngl.pdb.gz)

**Comment by fredludlow** [comment]
Two problems here: 

1) You're hitting the limits of the PDB format again. That file has 180000 atoms in it and some of them have repeated serial numbers. The PDB format only has 5 columns to declare the (unique!) serial number for an atom so can only cope with 99999 atoms. There are hacks to get around this, I think NGL supports hexidecimal atom IDs, see #241, but I've never used this.

2) I think the selection oddities are due to the fact that you're overflowing the maximum number of atoms allowed in a residue (stored as unsigned 16 bit int here: https://github.com/nglviewer/ngl/blob/2d84a993/src/store/residue-store.ts#L15). 

So, options:
1) Quick - bump up  the various typed arrays to UInt32 rather than UInt16 (but at a memory use/efficiency cost...)
1a) Do this intelligently based on structure size
2) Sort-of-quick - fix the input (increment the residue number every 10000 lines or so? Use another file format?)
3) Allow use of atomSets (bitarrays) to directly specify selections (see this ancient issue which I've been wanting to look at forever but never gets to the top of the list: #269)

**Comment by fredludlow** [comment]
I think #825 closes this - feel free to reopen if not

**Comment by appassionate** [comment]
@fredludlow sorry to ask a related question in this closed issue. : )
I'm using nglview to update representation by atom index in nglview.  

It seems like that:   (related to JS/TS code?)
```typescript
updateRepresentation("spacefill", {
      side: "front", sphereDetail: 0, radiusType: "covalent", scale: 0.5, color: "red",
      sele: "@0,1,2,1000,10000"
    })
```
I mean ... I want to change  color of some **selected** atoms in a "added" spacefill representation. But it failed in nglview, which lead to “all red” . 
Is there any way to select atoms successfully to change color? or this way might be not efficient in a iteration...?  thanks!

**Comment by ppillot** [comment]
@appassionate coloring is distinct from representation. Check selection based coloring in this page to see how you can do that https://nglviewer.org/ngl/api/manual/coloring.html
