### ISSUE TITLE
How to use NGL in vue

### ISSUE THREAD

**Issue by dahaigui** [nglviewer/ngl#918]
I am using vue, but found that there is no vue version of the NGL plugin, how can I port the code in NGL.js to my vue code?

I have installed NGL in vue。

However, I found that such code cannot be displayed in the browser during use. I found that there is a problem here through console.log(loadStructureButton), and the function definition cannot be performed. How should this be solved?

The code looks like this

![image](https://user-images.githubusercontent.com/47802187/159488569-e5483c3f-08d9-4f3a-940e-90aeacd162ba.png)
![image](https://user-images.githubusercontent.com/47802187/159488739-e146dd70-0286-42d9-9e78-e6bfee790261.png)
![image](https://user-images.githubusercontent.com/47802187/159488825-ae80daa6-d757-4d35-a6e5-fdf34ec5f0ba.png)
![image](https://user-images.githubusercontent.com/47802187/159488875-fe5ebf1d-74f1-46d2-9e3b-be79c0ff7f51.png)
![image](https://user-images.githubusercontent.com/47802187/159488922-157873c6-33f5-4129-81da-1e09637d69ff.png)

**Comment by fredludlow** [comment]
I'm not familiar with vue but know a few people do use it with NGL - if anyone can point to some resources please do!

**Comment by harryjubb** [comment]
@dahaigui Does your example work if you include the built version of NGL using a script tag, and using `window.NGL`, rather than the ES modules import? Have had issues trying to use NGL with Vue via `import` in the past.

**Comment by fredludlow** [comment]
@dahaigui, did Harry's comment help? Closing for now

**Comment by dahaigui** [comment]
> @dahaigui, did Harry's comment help? Closing for now

Yes, his suggestion helped me, thank you for your attention.

**Comment by everXXfor** [comment]
> @dahaigui Does your example work if you include the built version of NGL using a script tag, and using `window.NGL`, rather than the ES modules import? Have had issues trying to use NGL with Vue via `import` in the past.
I tried to reference it using a script tag in Vue2, but it still doesn't work. The error shown in the following link appeared. Thanks. 
![Prtsc:2023-04-01 201730](https://user-images.githubusercontent.com/103046033/229288164-40865185-009d-4231-989b-36777bbe149f.jpg)

**Comment by everXXfor** [comment]
> @dahaigui Does your example work if you include the built version of NGL using a script tag, and using , rather than the ES modules import? Have had issues trying to use NGL with Vue via in the past.`window.NGL``import`
I tried to reference it using a script tag in Vue2, but it still doesn't work. The error shown in the following picture appeared. Could you please help me with this issue? Thanks a lot.
![Uploading Error 2023-04-01 201730.jpg…]()

**Comment by everXXfor** [comment]
> @dahaigui Does your example work if you include the built version of NGL using a script tag, and using `window.NGL`, rather than the ES modules import? Have had issues trying to use NGL with Vue via `import` in the past.

I tried to reference it using a script tag in Vue2, but it still doesn't work. The error shown in the following picture appeared. Could you please help me with this issue? Thanks a lot.
![Error 2023-04-01 201730](https://user-images.githubusercontent.com/103046033/229288813-13e517ae-9573-4368-8f40-f3b75dac862b.jpg)

**Comment by everXXfor** [comment]
> @harryjubb 

I tried to reference it using a script tag in Vue2, but it still doesn't work. The error shown in the following picture appeared. Could you please help me with this issue? Thanks a lot.
![Error 2023-04-01 201730](https://user-images.githubusercontent.com/103046033/229291556-6255e091-0f97-4acc-9c35-325707b9e2cf.jpg)

**Comment by ppillot** [comment]
There seems to be an issue with the ngl.js loading itself. The "Unexpected token" message hints towards that.
Maybe you can try by adding the script tag to the HTML document directly. The page will execute when all the scripts are loaded so you'll be safe.

**Comment by everXXfor** [comment]
> There seems to be an issue with the ngl.js loading itself. The "Unexpected token" message hints towards that. Maybe you can try by adding the script tag to the HTML document directly. The page will execute when all the scripts are loaded so you'll be safe.

Thanks for your response. I was able to use ngl.js successfully in an HTML page, but unfortunately, I failed to make it work in a Vue 2 project. 
![ 2023-04-01](https://user-images.githubusercontent.com/103046033/229297023-e951383d-97ac-444e-a048-c3aeb4a685c1.jpg)
 And I wanna to know how to use it in Vue2

**Comment by everXXfor** [comment]
> There seems to be an issue with the ngl.js loading itself. The "Unexpected token" message hints towards that. Maybe you can try by adding the script tag to the HTML document directly. The page will execute when all the scripts are loaded so you'll be safe.

Thanks for your response. Do you mean do it like this?  If that's the case, unfortunately, it still won't be able to run properly.
![1](https://user-images.githubusercontent.com/103046033/229299177-efc6147b-4b6a-4897-8b4d-73b834d9f76f.jpg)
![2](https://user-images.githubusercontent.com/103046033/229299183-eef168a6-a2b3-4035-a7b4-689b322c951e.jpg)

**Comment by ppillot** [comment]
Yes, that's a possibility.
Anyway, the error seems to come from the ngl.js file itself. It looks like its content is corrupted. You might want to download it again.

**Comment by everXXfor** [comment]
> Yes, that's a possibility. Anyway, the error seems to come from the ngl.js file itself. It looks like its content is corrupted. You might want to download it again.

I have tried versions 2.0.1, 2.0.2, and the latest 2.1.0 version of ngl.js, but I still get the error 'Stage is undefined'
![ 2023-04-02 094208](https://user-images.githubusercontent.com/103046033/229326457-44b4091e-3f93-41cc-8f48-07d35e0fbf4d.jpg)

**Comment by harryjubb** [comment]
@everXXfor take a look at the`ngl.js` file.

Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?

The error shown in the console:

```Uncaught SyntaxError: unexpected token '<'```

Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.

It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.

If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.

Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.

**Comment by everXXfor** [comment]
> @everXXfor take a look at the`ngl.js` file.
> 
> Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?
> 
> The error shown in the console:
> 
> `Uncaught SyntaxError: unexpected token '<'`
> 
> Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.
> 
> It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.
> 
> If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.
> 
> Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.

Thank you so much for your reply and help.

 Following your advice, I made some corrections and the content of ngl.js is JavaScript, and the stage appeared. Unfortunately, the stage may not have successfully loaded the data from pdb1crn.ent.gz, resulting in a blank display. But when I opened it with HTML instead of Vue2, it could be loaded and displayed normally. Therefore, I ruled out the possibility that the data in the pdb1crn.ent.gz file was incorrect. 

And now, I still don't know what went wrong that prevented the stage from displaying the model from the pdb1crn.ent.gz file properly. 

Thanks again for your help. Here are some screenshots of the running program.
![2](https://user-images.githubusercontent.com/103046033/229580135-35674346-b21a-41a7-88dc-7cd19d6aa116.jpg)
![3](https://user-images.githubusercontent.com/103046033/229580166-ced8a563-3335-46a5-bd39-8e2d46f5cbf0.jpg)
![4](https://user-images.githubusercontent.com/103046033/229580192-caec5438-3066-41d4-a371-fecd10079d5e.jpg)
![5](https://user-images.githubusercontent.com/103046033/229580210-4f2f5b3d-02c0-487c-85a2-40caad782090.jpg)

**Comment by everXXfor** [comment]
> @everXXfor take a look at the`ngl.js` file.
> 
> Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?
> 
> The error shown in the console:
> 
> `Uncaught SyntaxError: unexpected token '<'`
> 
> Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.
> 
> It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.
> 
> If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.
> 
> Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.

Thank you so much for your reply and help!

 Following your advice, I made some corrections and the content of ngl.js is JavaScript, and the stage appeared. Unfortunately, the stage may not have successfully loaded the data from pdb1crn.ent.gz, resulting in a blank display. But when I opened it with HTML instead of Vue2, it could be loaded and displayed normally. Therefore, I ruled out the possibility that the data in the pdb1crn.ent.gz file was incorrect. And now, I still don't know what went wrong that prevented the stage from displaying the model from the pdb1crn.ent.gz file properly. 

Thanks again for your help. Here are some screenshots of the running program.
![2](https://user-images.githubusercontent.com/103046033/229667490-4a27a319-7206-4a4c-82ff-05a65c64cdc7.jpg)
![3](https://user-images.githubusercontent.com/103046033/229667508-08f04cff-88c0-4130-aa5d-09dba93a2dfa.jpg)
![4](https://user-images.githubusercontent.com/103046033/229667518-b0e1fe48-2252-4914-823a-f6c36cf
![5](https://user-images.githubusercontent.com/103046033/229667535-fd0a877f-e542-40be-bb0e-221e7fec2d60.jpg)
42e3f.jpg)

**Comment by everXXfor** [comment]
> > @everXXfor take a look at the`ngl.js` file.
> > Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?
> > The error shown in the console:
> > `Uncaught SyntaxError: unexpected token '<'`
> > Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.
> > It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.
> > If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.
> > Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.
> 
> Thank you so much for your reply and help!
> 
> Following your advice, I made some corrections and the content of ngl.js is JavaScript, and the stage appeared. Unfortunately, the stage may not have successfully loaded the data from pdb1crn.ent.gz, resulting in a blank display. But when I opened it with HTML instead of Vue2, it could be loaded and displayed normally. Therefore, I ruled out the possibility that the data in the pdb1crn.ent.gz file was incorrect. And now, I still don't know what went wrong that prevented the stage from displaying the model from the pdb1crn.ent.gz file properly.
> 
> Thanks again for your help. Here are some screenshots of the running program. ![2](https://user-images.githubusercontent.com/103046033/229667490-4a27a319-7206-4a4c-82ff-05a65c64cdc7.jpg) ![3](https://user-images.githubusercontent.com/103046033/229667508-08f04cff-88c0-4130-aa5d-09dba93a2dfa.jpg) ![4](https://user-images.githubusercontent.com/103046033/229667518-b0e1fe48-2252-4914-823a-f6c36cf ![5](https://user-images.githubusercontent.com/103046033/229667535-fd0a877f-e542-40be-bb0e-221e7fec2d60.jpg) 42e3f.jpg)
![4](https://user-images.githubusercontent.com/103046033/229667934-0ab5a1ed-fafe-4b25-8af9-f8a75883eb5d.jpg)

**Comment by everXXfor** [comment]
> @everXXfor take a look at the`ngl.js` file.
> 
> Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?
> 
> The error shown in the console:
> 
> `Uncaught SyntaxError: unexpected token '<'`
> 
> Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.
> 
> It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.
> 
> If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.
> 
> Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.

Thank you so much for your reply and help!

Following your advice, I made some corrections and the content of ngl.js is JavaScript, and the stage appeared. Unfortunately, the stage may not have successfully loaded the data from pdb1crn.ent.gz, resulting in a blank display. But when I opened it with HTML instead of Vue2, it could be loaded and displayed normally. Therefore, I ruled out the possibility that the data in the pdb1crn.ent.gz file was incorrect. And now, I still don't know what went wrong that prevented the stage from displaying the model from the pdb1crn.ent.gz file properly.

Thanks again for your help. Here are some screenshots of the running program.

![2](https://user-images.githubusercontent.com/103046033/229668129-e0b92a1d-a713-49b3-a521-c5f7b997beb7.jpg)

![3](https://user-images.githubusercontent.com/103046033/229668143-ba577304-c69e-4081-99ba-a89fdc947469.jpg)
![4](https://user-images.githubusercontent.com/103046033/229668152-b49d782a-b75c-447e-ae38-e323c2ea5470.jpg)
![5](https://user-images.githubusercontent.com/103046033/229668165-b81b2ef1-ed8a-4cc4-aa4c-e4965ae71e32.jpg)

**Comment by everXXfor** [comment]
> @everXXfor take a look at the`ngl.js` file.
> 
> Do this from the browser's developer tools, from the network tab. Does it look like JavaScript code?
> 
> The error shown in the console:
> 
> `Uncaught SyntaxError: unexpected token '<'`
> 
> Indicates that the content of `ngl.js` is likely HTML rather than JavaScript, where the `<` is likely from an HTML tag. If I was to hazard a guess, I suspect that the path given to `ngl.js` is not where the development server is actually hosting the file (if at all), and that the development server is returning e.g. a `404` or other error status HTML page to indicate that the content is not found. You should be able to see the status code of the request for `ngl.js` in the network tab as well.
> 
> It would be helpful to have more details on how you're running your app. I can see that WebPack Development Server (WDS) is in play from the console logs.
> 
> If it's the case that `ngl.js` is returning a `404` or other content that's HTML rather than the file, you'll need to look at the documentation for your toolchain if you're using something like Vue CLI, for where to place static files, and for the path that the development server will serve them from. Or if you have an e.g. manual WebPack setup, ensure that `ngl.js` is being served as a static file by the WDS, and that the path for that file is correct in your code. With the current path in the `script` tag, if `js/dist` is not being served by the WDS, then the browser will not be able to fetch the file.
> 
> Because `ngl.js` is not being executed, `NGL` is `undefined`, which is why you get the error `Cannot read property 'Stage' of undefined` when trying to use the NGL API.

Thank you sincerely. I have managed to load it into my stage successfully.
![22222](https://user-images.githubusercontent.com/103046033/229972975-24782532-198f-42df-b65f-8f2b4dea0063.jpg)
